subscribers:

  camera_reading:
    topic: /water_astra_rgbd/rgb/image_raw
    #topic: /object_analytics/rgb
    queue_size: 1

  depth_reading:
    topic: /water_astra_rgbd/depth_registered/image
    queue_size: 1
  
  camera_info:
    topic: /water_astra_rgbd/depth/camera_info
    queue_size: 1

actions:

  camera_reading:
    name: /darknet_ros/check_for_objects

publishers:

  object_detector:
    topic: /darknet_ros/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    #topic: /darknet_ros/bounding_boxes
    topic: /object_analytics/detection
    queue_size: 1
    latch: false

  detection_image:
    topic: /darknet_ros/detection_image
    queue_size: 1
    latch: true

  object_pose:
    topic: /darknet_ros/object_pose
    queue_size: 1
    latch: false





image_view:

  enable_opencv: false
  wait_key_delay: 1
  enable_console_output: false
